name: kre8sions
favicon: null
layout_spectrum: 0.7906766417436302
typography_spectrum: 0.07929325080476701
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9892111339140683
  lightness: 0.6148135585244745
  saturation: 0.6464723548851907
  rhythmicContrast: 0.10159147530794144
purpose: []
